### ISSUE TITLE
Configuration isn't replaced

### ISSUE THREAD

**Issue by chrispadgettlivecom** [manishtiwari25/BuildAzureB2cPolicies#12]
Any configuration settings, other than `Tenant`, aren't being replaced.

This is because the regular expression is matching on the JSON property pair:

```
if (jsonProperties != null)
{
    foreach (var property in jsonProperties)
    {
        var propertyValue = (string)property.Value;
        updatedPolicy = Regex.Replace(updatedPolicy, "{Settings:" + property + "}", propertyValue);
    }
}
```

Rather than the JSON property name:

```
if (jsonProperties != null)
{
    foreach (JProperty property in jsonProperties)
    {
        var propertyValue = (string)property.Value;
        updatedPolicy = Regex.Replace(updatedPolicy, "{Settings:" + property.Name + "}", propertyValue);
    }
}
```

**Comment by manishtiwari25** [comment]
thank you for reporting the issue @chrispadgettlivecom , I will look into it.

**Comment by manishtiwari25** [comment]
@chrispadgettlivecom  it appears to be working for me, can you confirm how you are passing the JSON. 

it should be like this. 
{
      "Tenant":"name",
      "ProxyIdentityExperienceFrameworkAppId":"guid",
      "IdentityExperienceFrameworkAppId":"guid"
}

and in b2c policy give like {Settings: <Json Property Name>}

**Comment by chrispadgettlivecom** [comment]
@manishtiwari25 Yes, that is equivalent to the JSON string that I'm using, except in the Visual Studio debugger it's matching on:

`{Settings:"MySettingName": "MySettingValue"}`

rather than:

`{Settings:MySettingName}`

**Comment by manishtiwari25** [comment]
@chrispadgettlivecom  I have updated the build task, Thanks for the help.
