### ISSUE TITLE
JSON values

### ISSUE THREAD

**Issue by tormodu** [manishtiwari25/BuildAzureB2cPolicies#7]
Can you please post an example of the json values format? I have tried the following format, but with no success:

{
"Tenant": "xxx",
"PolicySettings": {
"key1": "value1",
"key2": "value2"
}     
}

**Comment by manishtiwari25** [comment]
hey @tormodu, I will add documentations shortly. 
can you provide some console screenshots (please remove sensitive data if any)? 
and please confirm that you have registered an application in B2C tenant and gave appropriate permissions.
